stBM(2,"tree6575",[0,"","","Common/blank.gif",0,"left","default","hand",1,0,22,240,-1,"solid",4,"#c3c7d3","#c3c7d3","","repeat-y",1,"Common/expand1_f.gif","Common/expand1_uf.gif",9,9,0,"","","","",0,0,3,1,"center",0,0]);
stBS("p0",[0,0]);
stIT("p0i0",["Master Menu\r\n","#","_self","","","","",36,26,"bold 8pt 'Arial'","#FFFFFF","none","transparent","Common/XPgarybanner1.gif","no-repeat","bold 8pt 'Arial'","#EDEDED","none","transparent","Common/XPgarybanner1.gif","no-repeat","bold 8pt 'Arial'","#EDEDED","none","transparent","Common/XPgarybanner1.gif","no-repeat","bold 8pt 'Arial'","#EDEDED","none","transparent","Common/XPgarybanner1.gif","no-repeat",1,0,"left","middle",0,0]);
stBS("p1",[,1],"p0");
stIT("p1i0",["Home","frm_Home.aspx",,,,"Common/home_f.gif","Common/home_f.gif",20,20,"8pt 'Arial'","#000000",,,"Common/XPgrayline.gif","repeat-y","8pt 'Arial'","#000000","underline",,"Common/XPgrayline.gif","repeat-y","8pt 'Arial'","#999999",,,"Common/XPgrayline.gif","repeat-y","8pt 'Arial'","#000000","underline",,"Common/XPgrayline.gif","repeat-y"],"p0i0");
stIT("p1i1",["Add Magazine","frm_Add_Magazine.aspx",,,,"Common/earth_f.gif","Common/earth_f.gif"],"p1i0");
//stIT("p1i2",["Project Gallery","frm_Admin_Project_Gallery.aspx",,,,"Common/template_f.gif","Common/template_f.gif"],"p1i0");
stIT("p1i3",["Welcome Message","frm_Master_Message.aspx",,,,"Common/book_f.gif","Common/book_f.gif"],"p1i0");
stIT("p1i4",["Expo Category","frm_Master_Expo_Category_Entry.aspx"],"p1i3");
stIT("p1i5",["News and Events","frm_News_Events.aspx"],"p1i3");
stIT("p1i6",["Testimonials","frm_Testimonials.aspx"],"p1i3");
stIT("p1i7",["Upload Data","Upload_Data.aspx"],"p1i3");
stES();
stIT("p0i1",["","",,,,"","",,6,,"#FFFFFF",,,"",,,,"none",,"",,,"#000000",,,"",,,,,,""],"p1i0");
stIT("p0i2",["Transaction Menu ",,,,,,,30,,,"#000000",,,"Common/XPgarybanner2.gif",,,"#666666",,,"Common/XPgarybanner2.gif",,,"#666666",,,"Common/XPgarybanner2.gif",,,"#666666",,,"Common/XPgarybanner2.gif"],"p0i0");
stBS("p2",[],"p1");
stIT("p2i0",["Change Registration Type","frm_Change_Registration_Type.aspx",,,,"Common/greenball_c.gif","Common/greenball_c.gif"],"p1i0");
stIT("p2i1",["Confirm Participant Queries","frm_Confirm_Participant_Query.aspx"],"p2i0");
stIT("p2i2",["Confirm User Visit","frm_Confirm_Participant_Visit_Details.aspx"],"p2i0");
stES();
stIT("p0i3",[],"p0i1");
stIT("p0i4",["Administration"],"p0i2");
stBS("p3",[],"p1");
stIT("p3i0",["Change Password","frm_Change_Password.aspx"],"p2i0");
stIT("p3i1",["Log Off","Default.aspx"],"p2i0");
stES();
stIT("p0i5",[],"p0i1");
stES();
stEM();
