stBM(2,"tree6575",[0,"","","Common/blank.gif",0,"left","default","hand",1,0,22,-1,-1,"solid",4,"#c3c7d3","#c3c7d3","","repeat-y",1,"Common/expand1_f.gif","Common/expand1_uf.gif",9,9,0,"","","","",0,0,3,1,"center",0,0]);
stBS("p0",[0,0]);
stIT("p0i0",["","","_self","","","","",20,6,"8pt 'Arial'","#FFFFFF","none","transparent","","repeat-y","8pt 'Arial'","#000000","none","transparent","","repeat-y","8pt 'Arial'","#000000","none","transparent","","repeat-y","8pt 'Arial'","#000000","underline","transparent","","repeat-y",1,0,"left","middle",235,0]);
stIT("p0i1",["Master Menu\r\n","#",,,,,,36,26,"bold 8pt 'Arial'",,,,"Common/XPgarybanner1.gif","no-repeat","bold 8pt 'Arial'","#EDEDED",,,"Common/XPgarybanner1.gif","no-repeat","bold 8pt 'Arial'","#EDEDED",,,"Common/XPgarybanner1.gif","no-repeat","bold 8pt 'Arial'","#EDEDED","none",,"Common/XPgarybanner1.gif","no-repeat",,,,,0],"p0i0");
stBS("p1",[,1],"p0");
stIT("p1i0",["Home","frm_Participant_Home.aspx","_parent",,,"Common/home_f.gif","Common/home_f.gif",,20,,"#000000",,,"Common/XPgrayline.gif",,,,"underline",,"Common/XPgrayline.gif",,,"#999999",,,"Common/XPgrayline.gif",,,,,,"Common/XPgrayline.gif",,,,,,0],"p0i0");
stIT("p1i1",["Paint Menu","","_self",,,"Common/face_f.gif","Common/face_f.gif"],"p1i0");
stBS("p2",[],"p0");
stIT("p2i0",["Master Company","frm_Master_Paint.aspx","_parent"],"p1i1");
stIT("p2i1",["Product Type","frm_Master_Paint_Product_Type.aspx","_parent"],"p2i0");
stIT("p2i2",["Product Information","frm_Master_Paint_Product.aspx","_parent"],"p2i0");
//stIT("p2i3",["Scheme Information","frm_Detail_Scheme_Bank_Financial_Institution.aspx","_parent"],"p2i0");
//stIT("p2i4",["Loan Information","frm_Detail_Loan_Bank_Financial_Institution.aspx","_parent"],"p2i0");
stES();
stES();
stIT("p0i2",[,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,0],"p0i0");
stIT("p0i3",["Administration Menu",,,,,,,30,,,"#000000",,,"Common/XPgarybanner2.gif",,,"#666666",,,"Common/XPgarybanner2.gif",,,"#666666",,,"Common/bg_01a.gif",,,"#666666",,,"Common/bg_01a.gif"],"p0i1");
stBS("p3",[],"p1");
stIT("p3i0",["Change Password","frm_Change_Participant_Password.aspx",,,,"Common/greenball_c.gif","Common/greenball_c.gif"],"p1i0");
stIT("p3i1",["Welcome Message","frm_Master_Participant_Welcome_Message.aspx"],"p3i0");
stIT("p3i2",["Exclusive Offers","Participant_Exclusive_Offers.aspx"],"p3i0");
stIT("p3i3",["Offers","Participant_Offers.aspx"],"p3i0");
//stIT("p3i4",["View Your Stall","View_Bank_Stall.aspx"],"p3i0");
//stIT("p3i5",["Upload Excelsheet","frm_UploadExcelSheet.aspx"],"p3i0");
stIT("p3i4",["User Visited","frm_User_Visit_Details.aspx"],"p3i0");
stIT("p3i5",["Help","\Documentation\Bank Exhibitor User Manual.doc"],"p3i0");
stIT("p3i6",["Log Off","Logout.aspx"],"p3i0");
stES();
stIT("p0i4",[],"p0i2");
stES();
stEM();